server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventory_db
    username: myuser
    password: fialka
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: inventory_management

  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: inventory_management

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: inventory-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer